Models/Brand.cs
namespace Ecommerce.Models
{
    public class Brand
    { 
        public int Id { get; set; }
        public string Name { get; set; }
        public string Logo { get; set; }
    }
}

Models/DB/Brand.cs
using System;
using System.Collections.Generic;

namespace Ecommerce.Models.DB
{
    public partial class Brand
    {
        public int Id { get; set; }
               
        public string? Name { get; set; }
        public string? Logo { get; set; }
    }
}

Controllers/BrandsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Ecommerce.Data;
using Ecommerce.Models;
 

namespace Ecommerce.Controllers
{
    public class BrandsController : Controller
    {
        private readonly EcommerceContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public BrandsController(EcommerceContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }
        //Get Brands
        public async Task<IActionResult> Index()
        {
            return _context.Brand != null ?
           View(await _context.Brand.ToListAsync()) :
                          Problem("Entity set 'EcommerceContext.Brand'  is null.");
        }

      

        // GET: Brands/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Brand == null)
            {
                return NotFound();
            }

            var brand = await _context.Brand
                .FirstOrDefaultAsync(m => m.Id == id);
            if (brand == null)
            {
                return NotFound();
            }

            return View(brand);
        }
        // GET: Brands/Create
        public IActionResult Create()
        {
            return View();
        }

        // Post : Brands/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Logo")] Brand brand)
        {
            if (ModelState.IsValid)
            {
                _context.Add(brand);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(brand);
        }
        // Get : Brands/Edit
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Brand == null)
            {
                return NotFound();
            }

            var brand = await _context.Brand.FindAsync(id);
                
            if (brand == null)
            {
                return NotFound();
            }

            return View(brand);
        }

        // Post : Brands/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Logo")] Brand brand)
        {
            if (id != brand.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(brand);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BrandExists(brand.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(brand);
        }
        // Get : Brands/Delete
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Brand == null)
            {
                return NotFound();
            }

            var brand = await _context.Brand
                .FirstOrDefaultAsync(m => m.Id == id);
            if (brand == null)
            {
                return NotFound();
            }

            return View(brand);
        }
        // POST: Brands/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Brand == null)
            {
                return Problem("Entity set 'EcommerceContext.Brand'  is null.");
            }
            var brand = await _context.Brand.FindAsync(id);
            if (brand != null)
            {
                _context.Brand.Remove(brand);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> UploadImage(Models.DB.Brand model, IFormFile imageFile)
        {
            if (ModelState.IsValid)
            {
                if (imageFile != null && imageFile.Length > 0)
                {
                    // Get the file name and extension
                    var fileName = Path.GetFileName(imageFile.FileName);
                    var extension = Path.GetExtension(fileName);

                    // Generate a unique file name
                    var uniqueFileName = Guid.NewGuid().ToString() + extension;


                    // Set the path where the image will be saved
                    var imagePath = Path.Combine(_webHostEnvironment.WebRootPath, "Images", uniqueFileName);

                    // Save the image to the server
                    using (var fileStream = new FileStream(imagePath, FileMode.Create))
                    {
                        await imageFile.CopyToAsync(fileStream);
                    }

                    // Update the model with the image path
                    model.Logo = "/Images/" + uniqueFileName;

                    // Save the updated model to the database


                    var entity = _context.Brand.Find(model.Id);
                    if (entity != null)
                    {
                        // Update the entity with the new image path
                        entity.Logo = model.Logo;

                        // Save changes to the database
                        _context.SaveChanges();
                    }

                }

                // Redirect to the index action after successful upload
                return RedirectToAction("Index");
            }

            // If the model state is invalid, return the view with validation errors
            return View(model);
        }
        private bool BrandExists(int id)
        {
            return (_context.Brand?.Any(e => e.Id == id)).GetValueOrDefault();
        }


    }
}

Views/Brands/Create.cshtml
@model Ecommerce.Models.Brand

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">

<h1>Create</h1>

<h4>Brand</h4>
<hr />
    
<div class="row">
    <div class="col-md-4">
    @using (Html.BeginForm("UploadImage", "Brands", FormMethod.Post, new { enctype = "multipart/form-data" }))
       {
        <form asp-action="Create" class="btn btn-primary">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                   @* <label asp-for="Id" class="control-label"></label>*@
                    <input asp-for="Id" class="form-control" type="hidden"/>
                    <span asp-validation-for="Id" class="text-danger"></span>
                </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Logo" class="control-label"></label>
                <input asp-for="Logo" class="form-control" type="file" />
                <span asp-validation-for="Logo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
        }
    </div>
</div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Brands/Delete.cshtml
@model Ecommerce.Models.Brand

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Brand</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Logo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Logo)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Brands/Details.cshtml
@model Ecommerce.Models.Brand

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Brand</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Logo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Logo)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Brands/Edit.cshtml
@model Ecommerce.Models.Brand

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Brand</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Logo" class="control-label"></label>
                <input asp-for="Logo" class="form-control" />
                <span asp-validation-for="Logo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Brands/Index.cshtml
@model IEnumerable<Ecommerce.Models.Brand>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>
<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
               
                @Html.DisplayNameFor(model => model.Logo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    <img src="@Url.Content("~/brand-logo/"+item.Logo)"  style="width:80px;height:80px"/>
                   @* @Html.DisplayFor(modelItem => item.Logo)*@
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Brands/UploadImage.cshtml
@{
    ViewData["Title"] = "UploadImage";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>UploadImage</h1>